[package]
name = "site"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
biblatex = "0.8"
wasm-bindgen = "0.2.84"
reqwest = "0.11.16"
wasm-bindgen-futures = "0.4.34"
